"""
models.py
Core data models shared across agents, orchestrator, and API.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class RiskTolerance(str, Enum):
    CONSERVATIVE = "CONSERVATIVE"
    MODERATE = "MODERATE"
    AGGRESSIVE = "AGGRESSIVE"


class InvestmentGoal(str, Enum):
    RETIREMENT = "RETIREMENT"
    WEALTH_GROWTH = "WEALTH_GROWTH"
    SHORT_TERM_SAVINGS = "SHORT_TERM_SAVINGS"
    EDUCATION = "EDUCATION"
    INCOME_GENERATION = "INCOME_GENERATION"


@dataclass
class ClientProfile:
    """Input profile submitted by a client/advisor."""
    name: str
    age: int
    annual_income: float
    current_savings: float
    monthly_investment_capacity: float
    investment_goal: InvestmentGoal
    time_horizon_years: int
    existing_debt: float = 0.0
    dependents: int = 0
    self_reported_risk_comfort: Optional[str] = None  # "low" | "medium" | "high"

    def to_dict(self) -> dict:
        d = self.__dict__.copy()
        d["investment_goal"] = self.investment_goal.value
        return d


@dataclass
class AgentRecommendation:
    """Structured output produced by any individual agent."""
    agent_name: str
    summary: str
    details: dict = field(default_factory=dict)
    confidence: float = 0.8  # 0.0 - 1.0
    warnings: list = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "agent_name": self.agent_name,
            "summary": self.summary,
            "details": self.details,
            "confidence": round(self.confidence, 2),
            "warnings": self.warnings,
        }


@dataclass
class AdvisoryReport:
    """Final aggregated output returned to the client."""
    client_name: str
    risk_profile: str
    recommended_allocation: dict
    market_outlook: str
    tax_notes: list
    action_items: list
    agent_breakdown: list
    disclaimer: str = (
        "This report is generated by an automated multi-agent system for "
        "educational/demo purposes and does not constitute licensed financial advice."
    )

    def to_dict(self) -> dict:
        return {
            "client_name": self.client_name,
            "risk_profile": self.risk_profile,
            "recommended_allocation": self.recommended_allocation,
            "market_outlook": self.market_outlook,
            "tax_notes": self.tax_notes,
            "action_items": self.action_items,
            "agent_breakdown": self.agent_breakdown,
            "disclaimer": self.disclaimer,
        }
